---
nginx_packages:
  - pcre
  - pcre-devel
  - zlib
  - wget
  - libxml2
  - libxml2-devel
  - libxslt-devel
  - libxslt
  - gcc
  - wget
  - make
  - libaio-devel
  - pcre-devel
  - openssl-devel
  - expat-devel
  - zlib-devel
  - libxslt-devel
  - gd-devel
  - GeoIP-devel
  - gperftools-devel
  - perl-ExtUtils-Embed
  - git
  - readline-devel
  - python3-jwcrypto