- name: Create download_cluster folder in /root if not exist
  file:
    path: "{{ download_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download composer installer
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  args:
    chdir: "{{ download_path }}/"

- name: Get HASH file for composer
  shell: php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  args:
    chdir: "{{ download_path }}/"
  register: verify_hash_file_composer

- name: Check HASH File Composer
  fail:
    msg: "HASH File Composer failed"
  when: verify_hash_file_composer.stdout != "Installer verified"

- name: Install composer
  shell: php composer-setup.php --install-dir=/bin/ --filename=composer
  args:
    chdir: "{{ download_path }}/"
  register: verify_install_composer

- name: Check if Composer is installed with success
  fail:
    msg: "Composer failed to be installed"
  when: '"successfully installed" not in verify_install_composer.stdout'

