---
- name: Copy webmail.{{ domain_name }}.conf nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/01-webmail.{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Copy webmail.{{ domain_name }}.conf php config
  template:
    src: php-fpm.conf.j2
    dest: "/etc/opt/remi/{{ domain_php_version }}/php-fpm.d/webmail.{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Download & Unarchive Roundcube
  unarchive:
    src: https://github.com/roundcube/roundcubemail/releases/download/1.4.7/roundcubemail-1.4.7-complete.tar.gz
    dest: /var/mails
    remote_src: yes
    extra_opts:
    - --transform
    - s/^roundcubemail-1.4.7/public_html/

- name: Change mails directory permission to 0755
  file: 
    path: /var/mails/public_html
    mode: '0755'
    owner: mails
    group: mails
    recurse: yes

- set_fact:
    roundcube_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits,hexdigits') }}"
    roundcube_des_key: "{{ lookup('password', '/dev/null length=24 chars=ascii_letters,digits,hexdigits') }}"

- debug:
    msg: "roundcube user password {{ roundcube_password }}"

- debug:
    msg: "roundcube_des_key {{ roundcube_des_key }}"

- name: Create a new database with name roundcube
  mysql_db:
    name: roundcube
    state: present
    login_password: "{{ mysql8_root_password }}"

- name: Create a new username roundcube and grant access to roundcube.* / postfix.*
  mysql_user:
    name: roundcube
    password: "{{ roundcube_password }}"
    priv: "roundcube.*:ALL/postfix.*:ALL"
    state: present
    login_password: "{{ mysql8_root_password }}"
    host: "localhost"

- name: Restore database roundcube
  mysql_db:
    name: roundcube
    login_user: roundcube
    login_password: "{{ roundcube_password }}"
    state: import
    target: "/var/mails/public_html/SQL/mysql.initial.sql"

- name: Copy config.inc.php roundcube config
  template:
    src: "rundcube_config.inc.php.j2"
    dest: "/var/mails/public_html/config/config.inc.php"
    owner: mails
    group: mails
    mode: '0644'


- name: Copy config.inc.php roundcube password plugin config
  template:
    src: "roundcube_password_config.inc.php.j2"
    dest: "/var/mails/public_html/plugins/password/config.inc.php"
    owner: mails
    group: mails
    mode: '0644'