---
- name: Stop Mysql if exist
  systemd:
    name: "mysqld"
    state: "stopped"
  ignore_errors: true

- name: Remove all Mysql packages | Mysql8
  # shell: yum remove mysql* -y
  dnf:
    name: '@mysql'
    state: absent

- name: Remove Mysql old data if exist
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/mysql
    - /var/log/mysql/mysqld.log
  ignore_errors: yes

- name: Install repo Mysql8 | mysql8
  yum:
     name: https://dev.mysql.com/get/mysql80-community-release-el8-1.noarch.rpm
     state: present