---
- name: Copy {{ domain_name }}.conf nginx config
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-enabled/01-{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Copy {{ domain_name }}.conf php config
  template:
    src: php-fpm.conf.j2
    dest: "/etc/opt/remi/{{ domain_php_version }}/php-fpm.d/{{ domain_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm